name: Build ZMK Firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout user config
        uses: actions/checkout@v4

      - name: Build firmware
        uses: zmkfirmware/zmk-build@v1
        with:
          board: nice_nano_v2
          shield: bat43
